function [FEATSYMBOL,FEATDESC]=FeatureDescrip()

	FEATSYMBOL{1} ='RATMAX';
	FEATSYMBOL{2} ='RATMIN';
	FEATSYMBOL{3} ='AVEPULS';
	FEATSYMBOL{4} ='RMSPULS';
	FEATSYMBOL{5} ='FWHMPULS{1}';
	FEATSYMBOL{6} ='AVEQT{ITWMAX}';
	FEATSYMBOL{7} ='SUMQT';
	FEATSYMBOL{8} ='AVEQTC{ITWMAX}';
	FEATSYMBOL{9} ='SUMQTC';
	FEATSYMBOL{10} ='SUMQRS';
	FEATSYMBOL{11} ='AVEPR{IPMAX}';
	FEATSYMBOL{12} ='RMSPR{IPMAX}';
	FEATSYMBOL{13} ='SUMPR';
	FEATSYMBOL{14} ='SUMRMSPR';
	FEATSYMBOL{15} ='PERCMAX';
	FEATSYMBOL{16} ='SUMNEG';
	FEATSYMBOL{17} ='TWMAXMAX{ITWMAX}';
	FEATSYMBOL{18} ='SUMRMSQT';
	FEATSYMBOL{19} ='SUMRMSQTC';
	FEATSYMBOL{20} ='SUMST';
	FEATSYMBOL{21} ='SUMRMSST';
	FEATSYMBOL{22} ='AVERATE';
	FEATSYMBOL{23} ='RMSRATE';
	FEATSYMBOL{24} ='ANGLEAVE';
	FEATSYMBOL{25} ='AVERTANGLE';
	FEATSYMBOL{26} ='NMISSED';
	FEATSYMBOL{27} ='PERCQTOMIT';
	FEATSYMBOL{28} ='PERCPROMIT';
	FEATSYMBOL{29} ='PERCSTOMIT';
	FEATSYMBOL{30} ='SUMNPW';
	FEATSYMBOL{31} ='RMSRTANGLE';
	FEATSYMBOL{32} ='AVEQRS{16}';
	FEATSYMBOL{33} ='RMSQRS{16}';
	FEATSYMBOL{34} ='AVEST{16}';
	FEATSYMBOL{35} ='RMSST{16}';
	FEATSYMBOL{36} ='AVEQT{16}';
	FEATSYMBOL{37} ='RMSQT{16}';
	FEATSYMBOL{38} ='AVEQTC{16}';
	FEATSYMBOL{39} ='RMSQTC{16}';
	FEATSYMBOL{40} ='AVEGAPAMP';
	FEATSYMBOL{41} ='RMSGAPAMP';
	FEATSYMBOL{42} ='AVEAREAQRS';
	FEATSYMBOL{43} ='AVEAREASTEND';
	FEATSYMBOL{44} ='AVERATIO';
	FEATSYMBOL{45} ='AVERMSQRSST';
	FEATSYMBOL{46} ='STELEVATE';
	FEATSYMBOL{47} ='AVESTELEV{1}';
	FEATSYMBOL{48} ='AVESTELEV{2}';
	FEATSYMBOL{49} ='AVESTELEV{3}';
	FEATSYMBOL{50} ='AVESTELEV{4}';
	FEATSYMBOL{51} ='AVESTELEV{5}';
	FEATSYMBOL{52} ='AVESTELEV{6}';
	FEATSYMBOL{53} ='AVESTELEV{7}';
	FEATSYMBOL{54} ='AVESTELEV{8}';
	FEATSYMBOL{55} ='AVESTELEV{9}';
	FEATSYMBOL{56} ='AVESTELEV{10}';
	FEATSYMBOL{57} ='AVESTELEV{11}';
	FEATSYMBOL{58} ='AVESTELEV{12}';
	FEATSYMBOL{59} ='AVESTELEV{13}';
	FEATSYMBOL{60} ='AVESTELEV{14}';
	FEATSYMBOL{61} ='AVESTELEV{15}';
	FEATSYMBOL{62} ='AVENUMPEAKS{1}';
	FEATSYMBOL{63} ='AVENUMPEAKS{2}';
	FEATSYMBOL{64} ='AVENUMPEAKS{3}';
	FEATSYMBOL{65} ='AVENUMPEAKS{4}';
	FEATSYMBOL{66} ='AVENUMPEAKS{5}';
	FEATSYMBOL{67} ='AVENUMPEAKS{6}';
	FEATSYMBOL{68} ='AVENUMPEAKS{7}';
	FEATSYMBOL{69} ='AVENUMPEAKS{8}';
	FEATSYMBOL{70} ='AVENUMPEAKS{9}';
	FEATSYMBOL{71} ='AVENUMPEAKS{10}';
	FEATSYMBOL{72} ='AVENUMPEAKS{11}';
	FEATSYMBOL{73} ='AVENUMPEAKS{12}';
	FEATSYMBOL{74} ='AVENUMPEAKS{13}';
	FEATSYMBOL{75} ='AVENUMPEAKS{14}';
	FEATSYMBOL{76} ='AVENUMPEAKS{15}';
	FEATSYMBOL{77} ='AVENUMPEAKS{16}';
	FEATSYMBOL{78} ='RWAVEMAX';
	FEATSYMBOL{79} ='RWAVEMIN';
	FEATSYMBOL{80} ='RWAVEAMPAVE';
	FEATSYMBOL{81} ='RWAVEAMPRMS';
	FEATSYMBOL{82} ='THMINAVE{1}';
	FEATSYMBOL{83} ='THMAXAVE{1}';
	FEATSYMBOL{84} ='SINPHMINAVE{1}';
	FEATSYMBOL{85} ='SINPHMAXAVE{1}';
	FEATSYMBOL{86} ='THMINAVE{2}';
	FEATSYMBOL{87} ='THMAXAVE{2}';
	FEATSYMBOL{88} ='SINPHMINAVE{2}';
	FEATSYMBOL{89} ='SINPHMAXAVE{2}';
	FEATSYMBOL{90} ='THMINAVE{3}';
	FEATSYMBOL{91} ='THMAXAVE{3}';
	FEATSYMBOL{92} ='SINPHMINAVE{3}';
	FEATSYMBOL{93} ='SINPHMAXAVE{3}';
	FEATSYMBOL{94} ='THRMSMAX{1}';
	FEATSYMBOL{95} ='THRMSMIN{1}';
	FEATSYMBOL{96} ='SINPHRMSMAX{1}';
	FEATSYMBOL{97} ='SINPHRMSMIN{1}';
	FEATSYMBOL{98} ='THRMSMAX{2}';
	FEATSYMBOL{99} ='THRMSMIN{2}';
	FEATSYMBOL{100} ='SINPHRMSMAX{2}';
	FEATSYMBOL{101} ='SINPHRMSMIN{2}';
	FEATSYMBOL{102} ='THRMSMAX{3}';
	FEATSYMBOL{103} ='THRMSMIN{3}';
	FEATSYMBOL{104} ='SINPHRMSMAX{3}';
	FEATSYMBOL{105} ='SINPHRMSMIN{3}';
	FEATSYMBOL{106} ='NSLOT';
	FEATSYMBOL{107} ='AVEPRSEG{16}';
	FEATSYMBOL{108} ='RMSPRSEG{16}';
	FEATSYMBOL{109} ='AVEPRINT{16}';
	FEATSYMBOL{110} ='RMSPRINT{16}';
	FEATSYMBOL{111} ='AVEPAMP{16}';
	FEATSYMBOL{112} ='RMSPAMP{16}';
	FEATSYMBOL{113} ='AVEEXTTH{1}';
	FEATSYMBOL{114} ='AVEEXTSINPH{1}';
	FEATSYMBOL{115} ='AVEEXTTH{2}';
	FEATSYMBOL{116} ='AVEEXTSINPH{2}';
	FEATSYMBOL{117} ='AVEEXTTH{3}';
	FEATSYMBOL{118} ='AVEEXTSINPH{3}';
	FEATSYMBOL{119} ='XIHEARTPAM';
	FEATSYMBOL{120} ='TWAVESUM';
	FEATSYMBOL{121} ='PERMISSED';
	FEATSYMBOL{122} ='AVEPAMP{1}';
	FEATSYMBOL{123} ='AVEPAMP{2}';
	FEATSYMBOL{124} ='AVEPAMP{3}';
	FEATSYMBOL{125} ='AVEPAMP{4}';
	FEATSYMBOL{126} ='AVEPAMP{5}';
	FEATSYMBOL{127} ='AVEPAMP{6}';
	FEATSYMBOL{128} ='AVEPAMP{7}';
	FEATSYMBOL{129} ='AVEPAMP{8}';
	FEATSYMBOL{130} ='AVEPAMP{9}';
	FEATSYMBOL{131} ='AVEPAMP{10}';
	FEATSYMBOL{132} ='AVEPAMP{11}';
	FEATSYMBOL{133} ='AVEPAMP{12}';
	FEATSYMBOL{134} ='AVEPAMP{13}';
	FEATSYMBOL{135} ='AVEPAMP{14}';
	FEATSYMBOL{136} ='AVEPAMP{15}';
	FEATSYMBOL{137} ='AVENMAXTP{1}';
	FEATSYMBOL{138} ='AVENMAXTP{2}';
	FEATSYMBOL{139} ='AVENMAXTP{3}';
	FEATSYMBOL{140} ='AVENMAXTP{4}';
	FEATSYMBOL{141} ='AVENMAXTP{5}';
	FEATSYMBOL{142} ='AVENMAXTP{6}';
	FEATSYMBOL{143} ='AVENMAXTP{7}';
	FEATSYMBOL{144} ='AVENMAXTP{8}';
	FEATSYMBOL{145} ='AVENMAXTP{9}';
	FEATSYMBOL{146} ='AVENMAXTP{10}';
	FEATSYMBOL{147} ='AVENMAXTP{11}';
	FEATSYMBOL{148} ='AVENMAXTP{12}';
	FEATSYMBOL{149} ='AVENMAXTP{13}';
	FEATSYMBOL{150} ='AVENMAXTP{14}';
	FEATSYMBOL{151} ='AVENMAXTP{15}';
	FEATSYMBOL{152} ='AVEQWAVE{1}';
	FEATSYMBOL{153} ='AVEQWAVE{2}';
	FEATSYMBOL{154} ='AVEQWAVE{3}';
	FEATSYMBOL{155} ='AVEQWAVE{4}';
	FEATSYMBOL{156} ='AVEQWAVE{5}';
	FEATSYMBOL{157} ='AVEQWAVE{6}';
	FEATSYMBOL{158} ='AVEQWAVE{7}';
	FEATSYMBOL{159} ='AVEQWAVE{8}';
	FEATSYMBOL{160} ='AVEQWAVE{9}';
	FEATSYMBOL{161} ='AVEQWAVE{10}';
	FEATSYMBOL{162} ='AVEQWAVE{11}';
	FEATSYMBOL{163} ='AVEQWAVE{12}';
	FEATSYMBOL{164} ='AVEQWAVE{13}';
	FEATSYMBOL{165} ='AVEQWAVE{14}';
	FEATSYMBOL{166} ='AVEQWAVE{15}';
	FEATSYMBOL{167} ='AVERWAVE{1}';
	FEATSYMBOL{168} ='AVERWAVE{2}';
	FEATSYMBOL{169} ='AVERWAVE{3}';
	FEATSYMBOL{170} ='AVERWAVE{4}';
	FEATSYMBOL{171} ='AVERWAVE{5}';
	FEATSYMBOL{172} ='AVERWAVE{6}';
	FEATSYMBOL{173} ='AVERWAVE{7}';
	FEATSYMBOL{174} ='AVERWAVE{8}';
	FEATSYMBOL{175} ='AVERWAVE{9}';
	FEATSYMBOL{176} ='AVERWAVE{10}';
	FEATSYMBOL{177} ='AVERWAVE{11}';
	FEATSYMBOL{178} ='AVERWAVE{12}';
	FEATSYMBOL{179} ='AVERWAVE{13}';
	FEATSYMBOL{180} ='AVERWAVE{14}';
	FEATSYMBOL{181} ='AVERWAVE{15}';
	FEATSYMBOL{182} ='AVESWAVE{1}';
	FEATSYMBOL{183} ='AVESWAVE{2}';
	FEATSYMBOL{184} ='AVESWAVE{3}';
	FEATSYMBOL{185} ='AVESWAVE{4}';
	FEATSYMBOL{186} ='AVESWAVE{5}';
	FEATSYMBOL{187} ='AVESWAVE{6}';
	FEATSYMBOL{188} ='AVESWAVE{7}';
	FEATSYMBOL{189} ='AVESWAVE{8}';
	FEATSYMBOL{190} ='AVESWAVE{9}';
	FEATSYMBOL{191} ='AVESWAVE{10}';
	FEATSYMBOL{192} ='AVESWAVE{11}';
	FEATSYMBOL{193} ='AVESWAVE{12}';
	FEATSYMBOL{194} ='AVESWAVE{13}';
	FEATSYMBOL{195} ='AVESWAVE{14}';
	FEATSYMBOL{196} ='AVESWAVE{15}';
	FEATSYMBOL{197} ='ANUMRP';
	FEATSYMBOL{198} ='AVERPAMP';
	FEATSYMBOL{199} ='AVERAT11';
	FEATSYMBOL{200} ='AVERAT12';

FEATDESC = {'RATMAX: MAXIMUM HEART RATE IN BEATS/MIN'
'RATMIN: MINIMUM HEART RATE IN BEATS/MIN'
'AVEPULS: AVERAGE TIME BETWEEN HEART BEATS IN SEC'
'RMSPULS: RMS DEVIATION OF THE MEAN HEART RATE IN BEATS/SEC'
'FWHMPULS{1}: FULL WIDTH AT HALF MAXIMUM FOR THE HEART RATE DISTRIBUTION'
'AVEQT{ITWMAX}: AVERAGE QT INTERVAL FOR LEAD WITH MAX. T WAVE'
'SUMQT: AVERAGE QT INTERVAL FOR ALL LEADS'
'AVEQTC{ITWMAX}: AVERAGE CORRECTED QT INTERVAL FOR LEAD WITH MAX. T WAVE'
'SUMQTC: AVERAGE CORRECTED QT INTERVAL FOR ALL LEADS'
'SUMQRS: AVERAGE QRS INTERVAL FOR ALL LEADS'
'AVEPR{IPMAX}: AVERAGE PR INTERVAL FOR LEAD WITH MAXIMUM P WAVE'
'RMSPR{IPMAX}: RMS DEV. OF PR INTERVALS - LEAD WITH THE MAXIMUM P WAVE'
'SUMPR: AVERAGE PR INTERVAL FOR ALL LEADS'
'SUMRMSPR: RMS DEVIATION FOR PR INTERVAL FOR ALL LEADS.'
'PERCMAX: PERCENTAGE OF NEGATIVE P WAVES FOR MAGNITUDE P WAVE LEAD'
'SUMNEG: AVERAGE PERCENTAGE OF NEGATIVE P WAVES FOR ALL LEADS'
'TWMAXMAX{ITWMAX}: MAXIMUM AMPLITUDE OF ANY T WAVE'
'SUMRMSQT: RMS DEVIATION OF QT INTERVALS'
'SUMRMSQTC: RMS DEVIATION OF CORRECTED QT INTERVALS'
'SUMST: AVERAGE ST SEGMENT LENGTH'
'SUMRMSST: RMS DEVIATION OF ST SEGMENT LENGTHS'
'AVERATE: AVERAGE HEART RATE IN BEATS/MIN'
'RMSRATE: RMS DEVIATION OF HEART RATE DISTRIBUTION IN BEATS/MIN '
'ANGLEAVE: AVERAGE HEART AXIS'
'AVERTANGLE: AVERAGE RT ANGLE OVER ALL BEATS IN AMPLITUDE SIGNAL'
'NMISSED: NUMBER OF MISSED R WAVES {BEATS}'
'PERCQTOMIT: % TOTAL QT INTERVALS NOT ANALYZED OR MISSING'
'PERCPROMIT: % TOTAL PR INTERVALS NOT ANALYZED OR MISSING'
'PERCSTOMIT: % TOTAL ST INTERVALS NOT ANALYZED OR MISSING'
'SUMNPW: AVERAGE NUMBER OF MAXIMA BETWEEN T WAVE AND P WAVE MAXIMA'
'RMSRTANGLE: RMS DEVIATION OF RT ANGLE FOR ALL BEATS'
'AVEQRS{16}: AVE. QRS FROM AMPLITUDE LEAD'
'RMSQRS{16}: RMS DEVIATION OF QRS FROM AMPLITUDE LEAD'
'AVEST{16}: AVE. ST SEGMENT FROM AMPLITUDE LEAD'
'RMSST{16}: RMS DEVIATION OF ST SEGMENT FROM AMPLITUDE LEAD'
'AVEQT{16}: AVE. QT INTERVAL FROM AMPLITUDE LEAD'
'RMSQT{16}: RMS DEVIATION OF QT INTERVAL FROM AMPLITUDE LEAD'
'AVEQTC{16}: AVE. BAZETTS CORRECTED QT INTERVAL FROM AMPLITUDE LEAD'
'RMSQTC{16}: REM DIVIATION OF CORRECTED QT INTERVAL FROM AMPLITUDE LEAD'
'AVEGAPAMP: AVE. R-R INTERVAL FROM AMPLITUDE LEAD'
'RMSGAPAMP: RMS DEVIATION OF R-R INTERVAL FROM AMPLITUDE LEAD'
'AVEAREAQRS: AVERAGE AREA UNDER QRS COMPLEXES'
'AVEAREASTEND: AVERAGE AREA UNDER S-T WAVE END'
'AVERATIO: AVERAGE RATIO OF QRS AREA TO S-TWAVE AREA'
'AVERMSQRSST: RMS DEV. RT ANGLE WITHIN EACH BEAT-ALL BEATS AMP. SIGNAL'
'STELEVATE: ST ELEVATION - AMPLITUDE SIGNAL'
'AVESTELEV{1}: AVE. ST ELEV. OVER ST SEGMENT LEAD 1: REF: P WAVE END'
'AVESTELEV{2}: AVE. ST ELEV. OVER ST SEGMENT LEAD 2: REF: P WAVE END'
'AVESTELEV{3}: AVE. ST ELEV. OVER ST SEGMENT LEAD 3: REF: P WAVE END'
'AVESTELEV{4}: AVE. ST ELEV. OVER ST SEGMENT LEAD AVR: REF: P WAVE END'
'AVESTELEV{5}: AVE. ST ELEV. OVER ST SEGMENT LEAD AVL: REF: P WAVE END'
'AVESTELEV{6}: AVE. ST ELEV. OVER ST SEGMENT LEAD AVF: REF: P WAVE END'
'AVESTELEV{7}: AVE. ST ELEV. OVER ST SEGMENT LEAD V1: REF: P WAVE END'
'AVESTELEV{8}: AVE. ST ELEV. OVER ST SEGMENT LEAD V2: REF: P WAVE END'
'AVESTELEV{9}: AVE. ST ELEV. OVER ST SEGMENT LEAD V3: REF: P WAVE END'
'AVESTELEV{10}: AVE. ST ELEV. OVER ST SEGMENT LEAD V4: REF: P WAVE END'
'AVESTELEV{11}: AVE. ST ELEV. OVER ST SEGMENT LEAD V5: REF: P WAVE END'
'AVESTELEV{12}: AVE. ST ELEV. OVER ST SEGMENT LEAD V6: REF: P WAVE END'
'AVESTELEV{13}: AVE. ST ELEV. OVER ST SEGMENT LEAD VX: REF: P WAVE END'
'AVESTELEV{14}: AVE. ST ELEV. OVER ST SEGMENT LEAD VY: REF: P WAVE END'
'AVESTELEV{15}: AVE. ST ELEV. OVER ST SEGMENT LEAD VZ: REF: P WAVE END'
'AVENUMPEAKS{1}: AVE. NUMBER EXTREMA IN QRS COMPLEX IN LEAD 1'
'AVENUMPEAKS{2}: AVE. NUMBER EXTREMA IN QRS COMPLEX IN LEAD 2'
'AVENUMPEAKS{3}: AVE. NUMBER EXTREMA IN QRS COMPLEX IN LEAD 3'
'AVENUMPEAKS{4}: AVE. NUMBER EXTREMA IN QRS COMPLEX IN LEAD AVR'
'AVENUMPEAKS{5}: AVE. NUMBER EXTREMA IN QRS COMPLEX IN LEAD AVL'
'AVENUMPEAKS{6}: AVE. NUMBER EXTREMA IN QRS COMPLEX IN LEAD AVF'
'AVENUMPEAKS{7}: AVE. NUMBER EXTREMA IN QRS COMPLEX IN LEAD V1'
'AVENUMPEAKS{8}: AVE. NUMBER EXTREMA IN QRS COMPLEX IN LEAD V2'
'AVENUMPEAKS{9}: AVE. NUMBER EXTREMA IN QRS COMPLEX IN LEAD V3'
'AVENUMPEAKS{10}: AVE. NUMBER EXTREMA IN QRS COMPLEX IN LEAD V4'
'AVENUMPEAKS{11}: AVE. NUMBER EXTREMA IN QRS COMPLEX IN LEAD V5'
'AVENUMPEAKS{12}: AVE. NUMBER EXTREMA IN QRS COMPLEX IN LEAD V6'
'AVENUMPEAKS{13}: AVE. NUMBER EXTREMA IN QRS COMPLEX IN LEAD VX'
'AVENUMPEAKS{14}: AVE. NUMBER EXTREMA IN QRS COMPLEX IN LEAD VY'
'AVENUMPEAKS{15}: AVE. NUMBER EXTREMA IN QRS COMPLEX IN LEAD VZ'
'AVENUMPEAKS{16}: AVE. NUMBER EXTREMA IN QRS COMPLEX IN SIGNAL AMPLITUDE'
'RWAVEMAX: MAXIMUM R WAVE AMPLITUDE IN LEAD USED FOR DETERMINATION'
'RWAVEMIN: MINIMUM R WAVE AMPLITUDE IN LEAD USED FOR DETERMINATION'
'RWAVEAMPAVE: AVERAGE R WAVE AMPLITUDE IN LEAD USED FOR DETERMINATION'
'RWAVEAMPRMS: RMS DEV. FOR R WAVE AMPLITUDE IN LEAD USED FOR DETN.'
'THMINAVE{1}: AVERAGE MINIMUM THETA ANGLE IN QRS COMPLEX'
'THMAXAVE{1}: AVERAGE MAXIMUM THETA ANGLE IN QRS COMPLEX'
'SINPHMINAVE{1}: AVERAGE MINIMUM SIN{PHI} IN QRS COMPLEX'
'SINPHMAXAVE{1}: AVERAGE MAXIMUM SIN{PHI} IN QRS COMPLEX'
'THMINAVE{2}: AVERAGE MINIMUM THETA ANGLE IN T WAVE'
'THMAXAVE{2}: AVERAGE MAXIMUM THETA ANGLE IN T WAVE'
'SINPHMINAVE{2}: AVERAGE MINIMUM SIN{PHI} IN T WAVE'
'SINPHMAXAVE{2}: AVERAGE MAXIMUM SIN{PHI} IN T WAVE'
'THMINAVE{3}: AVERAGE MINIMUM THETA ANGLE IN P WAVE'
'THMAXAVE{3}: AVERAGE MAXIMUM THETA ANGLE IN P WAVE'
'SINPHMINAVE{3}: AVERAGE MINIMUM SIN{PHI} IN P WAVE'
'SINPHMAXAVE{3}: AVERAGE MAXIMUM SIN{PHI} IN P WAVE'
'THRMSMAX{1}: RMS DEV. DISTRIBUTION OF MAXIMUM THETA ANGLES QRS COMPLEX'
'THRMSMIN{1}: RMS DEV. DISTRIBUTION OF MINIMUM THETA ANGLES QRS COMPLEX'
'SINPHRMSMAX{1}: RMS DEV. DISTRIBUTION OF MAX. SIN{PHI} ANGLES QRS'
'SINPHRMSMIN{1}: RMS DEV. DISTRIBUTION OF MAX. SIN{PHI} ANGLES QRS'
'THRMSMAX{2}: RMS DEV. DISTRIBUTION OF MAXIMUM THETA ANGLES T WAVE'
'THRMSMIN{2}: RMS DEV. DISTRIBUTION OF MINIMUM THETA ANGLES T WAVE'
'SINPHRMSMAX{2}: RMS DEV. DISTRIBUTION OF MAX. SIN{PHI} ANGLES T WAVE'
'SINPHRMSMIN{2}: RMS DEV. DISTRIBUTION OF MAX. SIN{PHI} ANGLES T WAVE'
'THRMSMAX{3}: RMS DEV. DISTRIBUTION OF MAXIMUM THETA ANGLES P WAVE'
'THRMSMIN{3}: RMS DEV. DISTRIBUTION OF MINIMUM THETA ANGLES P WAVE'
'SINPHRMSMAX{3}: RMS DEV. DISTRIBUTION OF MAX. SIN{PHI} ANGLES P WAVE'
'SINPHRMSMIN{3}: RMS DEV. DISTRIBUTION OF MAX. SIN{PHI} ANGLES P WAVE'
'NSLOT:  IF = 0, P WAVE IS NOT SLOTTED; IF = 1, IT IS SLOTTED'
'AVEPRSEG{16}: AVERAGE PR SEGMENT FOR AMPLITUDE SIGNAL'
'RMSPRSEG{16}: RMS DEVIATION OF PR SEGMENT FOR AMPLITUDE SIGNAL'
'AVEPRINT{16}: AVERAGE PR INTERVAL FOR AMPLITUDE SIGNAL'
'RMSPRINT{16}: RMS DEVIATION OF PR INTERVAL FOR AMPLITUDE SIGNAL'
'AVEPAMP{16}: AVE. P WAVE AMPLITUDE REL. TO NEXT Q AMP. - AMPLITUDE SIG.'
'RMSPAMP{16}: RMS DEV. OF P WAVE AMPLITUDE IN AMPLITUDE SIGNAL'
'AVEEXTTH{1}: AVE. NUMBER OF EXTREMA IN THETA DIST.- QRS WAVE AMP. SIG.'
'AVEEXTSINPH{1}: AVE. NUMBER OF EXTREMA IN SIN{PHI} DIST.- QRS WAVE AMP.'
'AVEEXTTH{2}: AVE. NUMBER OF EXTREMA IN THETA DIST.- T WAVE AMP. SIG.'
'AVEEXTSINPH{2}: AVE. NUMBER OF EXTREMA IN SIN{PHI} DIST.- T WAVE AMP.'
'AVEEXTTH{3}: AVE. NUMBER OF EXTREMA IN THETA DIST.- P WAVE AMP. SIG.'
'AVEEXTSINPH{3}: AVE. NUMBER OF EXTREMA IN SIN{PHI} DIST.- P WAVE AMP.'
'XIHEARTPAM: AXIS: 1=NORMAL, 2=RIGHT DEV., 3=EXT. RIGHT DEV., 4=LEFT DEV'
'TWAVESUM: NUMBER OF NEG., INVERTED, T WAVES LEADS 1-12 EXCEPT AVR'
'PERMISSED: PERCENTAGE OF MISSED R WAVES'
'AVEPAMP{1}: AVERAGE P WAVE AMPLITUDE IN LEAD 1'
'AVEPAMP{2}: AVERAGE P WAVE AMPLITUDE IN LEAD 2'
'AVEPAMP{3}: AVERAGE P WAVE AMPLITUDE IN LEAD 3'
'AVEPAMP{4}: AVERAGE P WAVE AMPLITUDE IN LEAD AVR'
'AVEPAMP{5}: AVERAGE P WAVE AMPLITUDE IN LEAD AVL'
'AVEPAMP{6}: AVERAGE P WAVE AMPLITUDE IN LEAD AVF'
'AVEPAMP{7}: AVERAGE P WAVE AMPLITUDE IN LEAD V1'
'AVEPAMP{8}: AVERAGE P WAVE AMPLITUDE IN LEAD V2'
'AVEPAMP{9}: AVERAGE P WAVE AMPLITUDE IN LEAD V3'
'AVEPAMP{10}: AVERAGE P WAVE AMPLITUDE IN LEAD V4'
'AVEPAMP{11}: AVERAGE P WAVE AMPLITUDE IN LEAD V5'
'AVEPAMP{12}: AVERAGE P WAVE AMPLITUDE IN LEAD V6'
'AVEPAMP{13}: AVERAGE P WAVE AMPLITUDE IN LEAD VX'
'AVEPAMP{14}: AVERAGE P WAVE AMPLITUDE IN LEAD VY'
'AVEPAMP{15}: AVERAGE P WAVE AMPLITUDE IN LEAD VZ'
'AVENMAXTP{1}: AVE. NUMB. MAXIMA BETWEEN T - P WAVE MAXIMA IN LEAD 1'
'AVENMAXTP{2}: AVE. NUMB. MAXIMA BETWEEN T - P WAVE MAXIMA IN LEAD 2'
'AVENMAXTP{3}: AVE. NUMB. MAXIMA BETWEEN T - P WAVE MAXIMA IN LEAD 3'
'AVENMAXTP{4}: AVE. NUMB. MAXIMA BETWEEN T - P WAVE MAXIMA IN LEAD AVR'
'AVENMAXTP{5}: AVE. NUMB. MAXIMA BETWEEN T - P WAVE MAXIMA IN LEAD AVL'
'AVENMAXTP{6}: AVE. NUMB. MAXIMA BETWEEN T - P WAVE MAXIMA IN LEAD AVF'
'AVENMAXTP{7}: AVE. NUMB. MAXIMA BETWEEN T - P WAVE MAXIMA IN LEAD V1'
'AVENMAXTP{8}: AVE. NUMB. MAXIMA BETWEEN T - P WAVE MAXIMA IN LEAD V2'
'AVENMAXTP{9}: AVE. NUMB. MAXIMA BETWEEN T - P WAVE MAXIMA IN LEAD V3'
'AVENMAXTP{10}: AVE. NUMB. MAXIMA BETWEEN T - P WAVE MAXIMA IN LEAD V4'
'AVENMAXTP{11}: AVE. NUMB. MAXIMA BETWEEN T - P WAVE MAXIMA IN LEAD V5'
'AVENMAXTP{12}: AVE. NUMB. MAXIMA BETWEEN T - P WAVE MAXIMA IN LEAD V6'
'AVENMAXTP{13}: AVE. NUMB. MAXIMA BETWEEN T - P WAVE MAXIMA IN LEAD VX'
'AVENMAXTP{14}: AVE. NUMB. MAXIMA BETWEEN T - P WAVE MAXIMA IN LEAD VY'
'AVENMAXTP{15}: AVE. NUMB. MAXIMA BETWEEN T - P WAVE MAXIMA IN LEAD VZ'
'AVEQWAVE{1}: AVERAGE Q WAVE MAGNITUDE IN LEAD 1'
'AVEQWAVE{2}: AVERAGE Q WAVE MAGNITUDE IN LEAD 2'
'AVEQWAVE{3}: AVERAGE Q WAVE MAGNITUDE IN LEAD 3'
'AVEQWAVE{4}: AVERAGE Q WAVE MAGNITUDE IN LEAD AVR'
'AVEQWAVE{5}: AVERAGE Q WAVE MAGNITUDE IN LEAD AVL'
'AVEQWAVE{6}: AVERAGE Q WAVE MAGNITUDE IN LEAD AVF'
'AVEQWAVE{7}: AVERAGE Q WAVE MAGNITUDE IN LEAD V1'
'AVEQWAVE{8}: AVERAGE Q WAVE MAGNITUDE IN LEAD V2'
'AVEQWAVE{9}: AVERAGE Q WAVE MAGNITUDE IN LEAD V3'
'AVEQWAVE{10}: AVERAGE Q WAVE MAGNITUDE IN LEAD V4'
'AVEQWAVE{11}: AVERAGE Q WAVE MAGNITUDE IN LEAD V5'
'AVEQWAVE{12}: AVERAGE Q WAVE MAGNITUDE IN LEAD V6'
'AVEQWAVE{13}: AVERAGE Q WAVE MAGNITUDE IN LEAD VX'
'AVEQWAVE{14}: AVERAGE Q WAVE MAGNITUDE IN LEAD VY'
'AVEQWAVE{15}: AVERAGE Q WAVE MAGNITUDE IN LEAD VZ'
'AVERWAVE{1}: AVERAGE R WAVE MAGNITUDE IN LEAD 1'
'AVERWAVE{2}: AVERAGE R WAVE MAGNITUDE IN LEAD 2'
'AVERWAVE{3}: AVERAGE R WAVE MAGNITUDE IN LEAD 3'
'AVERWAVE{4}: AVERAGE R WAVE MAGNITUDE IN LEAD AVR'
'AVERWAVE{5}: AVERAGE R WAVE MAGNITUDE IN LEAD AVL'
'AVERWAVE{6}: AVERAGE R WAVE MAGNITUDE IN LEAD AVF'
'AVERWAVE{7}: AVERAGE R WAVE MAGNITUDE IN LEAD V1'
'AVERWAVE{8}: AVERAGE R WAVE MAGNITUDE IN LEAD V2'
'AVERWAVE{9}: AVERAGE R WAVE MAGNITUDE IN LEAD V3'
'AVERWAVE{10}: AVERAGE R WAVE MAGNITUDE IN LEAD V4'
'AVERWAVE{11}: AVERAGE R WAVE MAGNITUDE IN LEAD V5'
'AVERWAVE{12}: AVERAGE R WAVE MAGNITUDE IN LEAD V6'
'AVERWAVE{13}: AVERAGE R WAVE MAGNITUDE IN LEAD VX'
'AVERWAVE{14}: AVERAGE R WAVE MAGNITUDE IN LEAD VY'
'AVERWAVE{15}: AVERAGE R WAVE MAGNITUDE IN LEAD VZ'
'AVESWAVE{1}: AVERAGE S WAVE MAGNITUDE IN LEAD 1'
'AVESWAVE{2}: AVERAGE S WAVE MAGNITUDE IN LEAD 2'
'AVESWAVE{3}: AVERAGE S WAVE MAGNITUDE IN LEAD 3'
'AVESWAVE{4}: AVERAGE S WAVE MAGNITUDE IN LEAD AVR'
'AVESWAVE{5}: AVERAGE S WAVE MAGNITUDE IN LEAD AVL'
'AVESWAVE{6}: AVERAGE S WAVE MAGNITUDE IN LEAD AVF'
'AVESWAVE{7}: AVERAGE S WAVE MAGNITUDE IN LEAD V1'
'AVESWAVE{8}: AVERAGE S WAVE MAGNITUDE IN LEAD V2'
'AVESWAVE{9}: AVERAGE S WAVE MAGNITUDE IN LEAD V3'
'AVESWAVE{10}: AVERAGE S WAVE MAGNITUDE IN LEAD V4'
'AVESWAVE{11}: AVERAGE S WAVE MAGNITUDE IN LEAD V5'
'AVESWAVE{12}: AVERAGE S WAVE MAGNITUDE IN LEAD V6'
'AVESWAVE{13}: AVERAGE S WAVE MAGNITUDE IN LEAD VX'
'AVESWAVE{14}: AVERAGE S WAVE MAGNITUDE IN LEAD VY'
'AVESWAVE{15}: AVERAGE S WAVE MAGNITUDE IN LEAD VZ'
'ANUMRP: AVERAGE NUMBER OF LEADS WITH NO R PRIME MAXIMA'
'AVERPAMP: AVERAGE AMPLITUDE OF R PRIME MAXIMA FOR ALL 15 LEADS'
'AVERAT11: AVE. SYM. RATIO FOR INVERTED T WAVES IN LEAD 11{0=NO INV.}'
'AVERAT12: AVE. SYM. RATIO FOR INVERTED T WAVES IN LEAD 11{0=NO INV.}'};

