function SAIDwaveletdesign(cmd,arg1,arg2,arg3)
% Wavelet filter GUI

me = 'Wavelet Filter Design';
% DEFAULTS
if nargin == 0, cmd = ''; else cmd = lower(cmd); end

% FIND WINDOW IF IT EXISTS
fig=findall(0,'type','figure','name',me);
if (size(fig,1)==0), fig=0; end

if length(get(fig,'children')) == 0, fig = 0; end

if fig
    WF = get(fig,'userdata');
end

%==================================================================
% Activate the window.
%
% ME() or ME('')
%==================================================================

if strcmp(cmd,'') | isempty(cmd)
    if fig        
        figure(fig)
        set(fig,'visible','on')
        WF.ECG = arg1.a;
        WF.info = arg1.info;
        WF.signal = WF.ECG(1,:);

        for i = 1:max(size(WF.info))
            infostr{1,i} = WF.info{i}.Lead;
        end

        set(WF.hpmlead,'String',infostr);
        wavestr = 'db2';
        SORH = 's';
        WF.T = [0 0 0 0 0 0 0 0 0 0];
        WF.wavestr = wavestr;
        WF.SORH = SORH;
        WF.filterno = arg2;
        
        set(fig,'userdata',WF);
        SAIDwaveletdesign('plot');
    else
        SAIDwaveletdesign('init',arg1,arg2);
    end
    %
    %==================================================================
    % Close the window.
    %
    % ME() or ME('')
    %==================================================================
elseif strcmp(cmd,'close')
    if exist(cat(2,tempdir,'waveletGUIdata.mat'))
        delete(cat(2,tempdir,'waveletGUIdata.mat'));
    end
    delete(fig);
    
elseif strcmp(cmd,'init')
    if fig == 0
        StdColor = get(0,'DefaultFigureColor');
        PointsToPixels = 72/get(0,'ScreenPixelsPerInch');
        StdUnit = 'character';

        uipos = getuipos;
        default = getdefaults;

        fig = figure('Units','points', ...
            'Interruptible','off', ...
            'BusyAction','cancel', ...
            'HandleVis','Callback', ...
            'Color',StdColor, ...
            'IntegerHandle','off', ...
            'MenuBar','none', ...
            'ToolBar','none', ...
            'Name',me, ...
            'NumberTitle','off', ...
            'PaperUnits','points', ...
            'Units', StdUnit, ...
            'Position',uipos.fig, ...
            'Tag','ImportIACfig', ...
            'Resize','off', ...
            'WindowStyle','normal');
        WF.frame1 = uicontrol('Parent',fig, ...
            'Unit',StdUnit, ...
            'BackgroundColor',StdColor, ...
            'Position',uipos.frame1, ...
            'Style','frame');
        WF.frame2 = uicontrol('Parent',fig, ...
            'Unit',StdUnit, ...
            'BackgroundColor',StdColor, ...
            'Position',uipos.frame2, ...
            'Style','frame');
        WF.error_messages= uicontrol('Parent',fig, ...
            'Units',StdUnit, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontWeight','bold', ...
            'ForegroundColor',[0 0 1], ...
            'ListboxTop',0, ...
            'Position',uipos.error_messages, ...
            'Style','text', ...
            'ToolTipStr','Feedback line with important messages for the user.',...
            'Tag','StaticText1');
        WF.Title_waveletGUI = uicontrol('Parent',fig, ...
            'Units',StdUnit, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',11, ...
            'FontWeight','bold', ...
            'ListboxTop',0, ...
            'Position',uipos.Title_waveletGUI, ...
            'String',me, ...
            'Style','text', ...
            'Tag','Title_waveletGUI');
        WF.hwavetype = uicontrol('Parent',fig, ...
            'Units',StdUnit, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',uipos.hwavetype, ...
            'String','Wavelet Type:', ...
            'horizontalAlignment','left',...
            'Style','text', ...
            'Tag','StaticTextwavetype');
        WF.hlead = uicontrol('Parent',fig, ...
            'Units',StdUnit, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',uipos.hlead, ...
            'horizontalAlignment','left',...
            'String','Lead Selection:', ...
            'Style','text', ...
            'Tag','StaticTextwaves');
        WF.hpmlead = uicontrol('Parent',fig, ...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''applydesignedfilter'')', ...
            'BackgroundColor',[1 1 1], ...
            'Units',StdUnit, ...
            'Style','popupmenu',...
            'String',{'I','II','III','IV'},...
            'Value',1,...
            'Position',uipos.hpmlead);
        WF.hwavethrhd = uicontrol('Parent',fig, ...
            'Units',StdUnit, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',uipos.hwavethrhd, ...
            'horizontalAlignment','left',...
            'String','Thresholding Method:', ...
            'Style','text', ...
            'Tag','StaticText32');
        WF.hfs = uicontrol('Parent',fig, ...
            'Units',StdUnit, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',uipos.hfs, ...
            'horizontalAlignment','left',...
            'String','Sampling Frequency:', ...
            'Style','text', ...
            'Tag','StaticText32');
        WF.hbandselection = uicontrol('Parent',fig, ...
            'Units',StdUnit, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',uipos.bandselection, ...
            'horizontalAlignment','left',...
            'String','Band Selection:', ...
            'Style','text', ...
            'Tag','StaticTextband');
        WF.hetfs = uicontrol('Parent',fig, ...
            'BackgroundColor',[1 1 1], ...
            'Units',StdUnit, ...
            'Style','edit',...
            'Enable','off',...
            'String','1000',...
            'Position',uipos.hetfs);
        WF.hfs1 = uicontrol('Parent',fig, ...
            'Units',StdUnit, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',uipos.hfs1, ...
            'String','HZ', ...
            'Style','text', ...
            'Tag','StaticTextfs1');
        WF.hpmwtype = uicontrol('Parent',fig, ...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''applydesignedfilter'')', ...
            'BackgroundColor',[1 1 1], ...
            'Units',StdUnit, ...
            'Style','popupmenu',...
            'String',{'Db2','Db10','sym2','Haar'},...
            'Value',1,...
            'Position',uipos.hpmwtype);

        WF.hpmwthrhd = uicontrol('Parent',fig, ...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''applydesignedfilter'')', ...
            'BackgroundColor',[1 1 1], ...
            'Units',StdUnit, ...
            'String',{'soft','hard'},...
            'Value',1,...
            'Position',uipos.hpmwthrhd, ...
            'Style','popupmenu');
        WF.rbh1 = uicontrol('Parent',fig,...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''applydesignedfilter'')', ...
            'Style','checkbox',...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'String','D1',...
            'Units',StdUnit, ...
            'Position',uipos.rbh1);
        WF.hetrb1 = uicontrol('Parent',fig, ...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''applydesignedfilter'')', ...
            'Units',StdUnit, ...
            'BackgroundColor',[1 1 1], ...
            'Style','edit',...
            'String','0',...
            'Position',uipos.hetrb1);
        WF.rbh2 = uicontrol('Parent',fig,...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''applydesignedfilter'')', ...
            'Style','checkbox',...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Units',StdUnit, ...
            'String','D2',...
            'Position',uipos.rbh2);
        WF.hetrb2 = uicontrol('Parent',fig, ...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''applydesignedfilter'')', ...
            'Units',StdUnit, ...
            'BackgroundColor',[1 1 1], ...
            'Style','edit',...
            'String','0',...
            'Position',uipos.hetrb2);
        WF.rbh3 = uicontrol('Parent',fig,...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''applydesignedfilter'')', ...
            'Style','checkbox',...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Units',StdUnit, ...
            'String','D3',...
            'Position',uipos.rbh3);
        WF.hetrb3 = uicontrol('Parent',fig, ...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''applydesignedfilter'')', ...
            'Units',StdUnit, ...
            'BackgroundColor',[1 1 1], ...
            'Style','edit',...
            'String','0',...
            'Position',uipos.hetrb3);
        WF.rbh4 = uicontrol('Parent',fig,...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''applydesignedfilter'')', ...
            'Style','checkbox',...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Units',StdUnit, ...
            'String','D4',...
            'Position',uipos.rbh4);
        WF.hetrb4 = uicontrol('Parent',fig, ...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''applydesignedfilter'')', ...
            'Units',StdUnit, ...
            'BackgroundColor',[1 1 1], ...
            'Style','edit',...
            'String','0',...
            'Position',uipos.hetrb4);
        WF.rbh5 = uicontrol('Parent',fig,...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''applydesignedfilter'')', ...
            'Style','checkbox',...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Units',StdUnit, ...
            'String','D5',...
            'Position',uipos.rbh5);
        WF.hetrb5 = uicontrol('Parent',fig, ...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''applydesignedfilter'')', ...
            'Units',StdUnit, ...
            'BackgroundColor',[1 1 1], ...
            'Style','edit',...
            'String','0',...
            'Position',uipos.hetrb5);
        WF.rbh6 = uicontrol('Parent',fig,...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''applydesignedfilter'')', ...
            'Style','checkbox',...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Units',StdUnit, ...
            'String','D6',...
            'Position',uipos.rbh6);
        WF.hetrb6 = uicontrol('Parent',fig, ...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''applydesignedfilter'')', ...
            'Units',StdUnit, ...
            'BackgroundColor',[1 1 1], ...
            'Style','edit',...
            'String','0',...
            'Position',uipos.hetrb6);
        WF.rbh7 = uicontrol('Parent',fig,...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''applydesignedfilter'')', ...
            'Style','checkbox',...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Units',StdUnit, ...
            'String','D7',...
            'Position',uipos.rbh7);
        WF.hetrb7 = uicontrol('Parent',fig, ...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''applydesignedfilter'')', ...
            'Units',StdUnit, ...
            'BackgroundColor',[1 1 1], ...
            'Style','edit',...
            'String','0',...
            'Position',uipos.hetrb7);
        WF.rbh8 = uicontrol('Parent',fig,...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''applydesignedfilter'')', ...
            'Style','checkbox',...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'String','D8',...
            'Units',StdUnit, ...
            'Position',uipos.rbh8);
        WF.hetrb8 = uicontrol('Parent',fig, ...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''applydesignedfilter'')', ...
            'Units',StdUnit, ...
            'BackgroundColor',[1 1 1], ...
            'Style','edit',...
            'String','0',...
            'Position',uipos.hetrb8);
        WF.rbh9 = uicontrol('Parent',fig,...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''applydesignedfilter'')', ...
            'Style','checkbox',...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Units',StdUnit, ...
            'String','D9',...
            'Position',uipos.rbh9);
        WF.hetrb9 = uicontrol('Parent',fig, ...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''applydesignedfilter'')', ...
            'Units',StdUnit, ...
            'BackgroundColor',[1 1 1], ...
            'Style','edit',...
            'String','0',...
            'Position',uipos.hetrb9);
        WF.rbh10 = uicontrol('Parent',fig,...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''applydesignedfilter'')', ...
            'Style','checkbox',...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Units',StdUnit, ...
            'String','D10',...
            'Position',uipos.rbh10);
        WF.hetrb10 = uicontrol('Parent',fig, ...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''applydesignedfilter'')', ...
            'Units',StdUnit, ...
            'BackgroundColor',[1 1 1], ...
            'Style','edit',...
            'String','0',...
            'Position',uipos.hetrb10);
        WF.Close_but = uicontrol('Parent',fig, ...
            'Units',StdUnit, ...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''close'')', ...
            'Enable','on', ...
            'ListboxTop',0, ...
            'Position',uipos.Close_but, ...
            'String','Close', ...
            'ToolTipStr','Close current wavelet filter design window',...
            'Tag','Pushbutton1');
        WF.OK_but = uicontrol('Parent',fig, ...
            'Units',StdUnit, ...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''ok'')', ...
            'Enable','on', ...
            'ListboxTop',0, ...
            'Position',uipos.OK_but, ...
            'String','OK', ...
            'ToolTipStr','Accomplish the wavelet filter design and return with the designed filter !',...
            'Tag','Pushbutton1');
        WF.design_but = uicontrol('Parent',fig, ...
            'Units',StdUnit, ...
            'Callback','SAIDutil(''SAIDwaveletdesign'',''plot'')', ...
            'Enable','on', ...
            'ListboxTop',0, ...
            'Position',uipos.design_but, ...
            'String','Design Filter', ...
            'ToolTipStr','Apply the design of wavelet filter with the setting of parameters!',...
            'Tag','Pushbutton1');
        WF.oriplot = axes('Parent',fig,...
            'Units',StdUnit, ...
            'Position',uipos.oriplot);
        WF.d1plot = axes('Parent',fig,...
            'Units',StdUnit, ...
            'Position',uipos.d1plot);
        WF.d2plot = axes('Parent',fig,...
            'Units',StdUnit, ...
            'Position',uipos.d2plot);
        WF.d3plot = axes('Parent',fig,...
            'Units',StdUnit, ...
            'Position',uipos.d3plot);
        WF.d4plot = axes('Parent',fig,...
            'Units',StdUnit, ...
            'Position',uipos.d4plot);
        WF.d5plot = axes('Parent',fig,...
            'Units',StdUnit, ...
            'Position',uipos.d5plot);
        WF.d6plot = axes('Parent',fig,...
            'Units',StdUnit, ...
            'Position',uipos.d6plot);
        WF.d7plot = axes('Parent',fig,...
            'Units',StdUnit, ...
            'Position',uipos.d7plot);
        WF.d8plot = axes('Parent',fig,...
            'Units',StdUnit, ...
            'Position',uipos.d8plot);
        WF.d9plot = axes('Parent',fig,...
            'Units',StdUnit, ...
            'Position',uipos.d9plot);
        WF.d10plot = axes('Parent',fig,...
            'Units',StdUnit, ...
            'Position',uipos.d10plot);
        WF.d1txt = uicontrol('Parent',fig, ...
            'Units',StdUnit, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',uipos.d1txt, ...
            'String','D1', ...
            'Style','text', ...
            'Tag','StaticTextd1');
        WF.d2txt = uicontrol('Parent',fig, ...
            'Units',StdUnit, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',uipos.d2txt, ...
            'String','D2', ...
            'Style','text', ...
            'Tag','StaticTextd2');
        WF.d3txt = uicontrol('Parent',fig, ...
            'Units',StdUnit, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',uipos.d3txt, ...
            'String','D3', ...
            'Style','text', ...
            'Tag','StaticTextd3');
        WF.d4txt = uicontrol('Parent',fig, ...
            'Units',StdUnit, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',uipos.d4txt, ...
            'String','D4', ...
            'Style','text', ...
            'Tag','StaticTextd4');
        WF.d5txt = uicontrol('Parent',fig, ...
            'Units',StdUnit, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',uipos.d5txt, ...
            'String','D5', ...
            'Style','text', ...
            'Tag','StaticTextd5');
        WF.d6txt = uicontrol('Parent',fig, ...
            'Units',StdUnit, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',uipos.d6txt, ...
            'String','D6', ...
            'Style','text', ...
            'Tag','StaticTextd6');
        WF.d7txt = uicontrol('Parent',fig, ...
            'Units',StdUnit, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',uipos.d7txt, ...
            'String','D7', ...
            'Style','text', ...
            'Tag','StaticTextd7');
        WF.d8txt = uicontrol('Parent',fig, ...
            'Units',StdUnit, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',uipos.d8txt, ...
            'String','D8', ...
            'Style','text', ...
            'Tag','StaticTextd8');
        WF.d9txt = uicontrol('Parent',fig, ...
            'Units',StdUnit, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',uipos.d9txt, ...
            'String','D9', ...
            'Style','text', ...
            'Tag','StaticTextd9');
        WF.d10txt = uicontrol('Parent',fig, ...
            'Units',StdUnit, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',uipos.d10txt, ...
            'String','D10', ...
            'Style','text', ...
            'Tag','StaticTextd10');

        WF.ECG = arg1.a;
        WF.info = arg1.info;
        WF.signal = WF.ECG(1,:);

        for i = 1:max(size(WF.info))
            infostr{1,i} = WF.info{i}.Lead;
        end

        set(WF.hpmlead,'String',infostr);
        wavestr = 'db2';
        SORH = 's';
        WF.T = [0 0 0 0 0 0 0 0 0 0];
        WF.wavestr = wavestr;
        WF.SORH = SORH;
        WF.filterno = arg2;

        set(WF.error_messages,'string',sprintf('Design Wavelet Filter for the EKG Signals.'));
        set(WF.rbh1,'value',default.rb1);
        set(WF.rbh2,'value',default.rb2);
        set(WF.rbh3,'value',default.rb3);
        set(WF.rbh4,'value',default.rb4);
        set(WF.rbh5,'value',default.rb5);
        set(WF.rbh6,'value',default.rb6);
        set(WF.rbh7,'value',default.rb7);
        set(WF.rbh8,'value',default.rb8);
        set(WF.rbh9,'value',default.rb9);
        set(WF.rbh10,'value',default.rb10);

        set(fig,'userdata',WF);
        SAIDwaveletdesign('plot');

    end


elseif strcmp(cmd,'applydesignedfilter')

    set(WF.OK_but,'enable','off');
    set(WF.Close_but,'enable','off');
    set(WF.design_but,'enable','off');

    if strcmp(get(WF.hetrb1,'string'),'0')
        cdt1 = 0;
    else
        cdt1 = str2num(get(WF.hetrb1,'string'));
    end
    if strcmp(get(WF.hetrb2,'string'),'0')
        cdt2 = 0;
    else
        cdt2 = str2num(get(WF.hetrb2,'string'));
    end
    if strcmp(get(WF.hetrb3,'string'),'0')
        cdt3 = 0;
    else
        cdt3 = str2num(get(WF.hetrb3,'string'));
    end
    if strcmp(get(WF.hetrb4,'string'),'0')
        cdt4 = 0;
    else
        cdt4 = str2num(get(WF.hetrb4,'string'));
    end
    if strcmp(get(WF.hetrb5,'string'),'0')
        cdt5 = 0;
    else
        cdt5 = str2num(get(WF.hetrb5,'string'));
    end
    if strcmp(get(WF.hetrb6,'string'),'0')
        cdt6 = 0;
    else
        cdt6 = str2num(get(WF.hetrb6,'string'));
    end
    if strcmp(get(WF.hetrb7,'string'),'0')
        cdt7 = 0;
    else
        cdt7 = str2num(get(WF.hetrb7,'string'));
    end
    if strcmp(get(WF.hetrb8,'string'),'0')
        cdt8 = 0;
    else
        cdt8 = str2num(get(WF.hetrb8,'string'));
    end
    if strcmp(get(WF.hetrb9,'string'),'0')
        cdt9 = 0;
    else
        cdt9 = str2num(get(WF.hetrb9,'string'));
    end
    if strcmp(get(WF.hetrb10,'string'),'0')
        cdt10 = 0;
    else
        cdt10 = str2num(get(WF.hetrb10,'string'));
    end
    if ~get(WF.rbh1,'value')
        cdt1 = 200;
    end
    if ~get(WF.rbh2,'value')
        cdt2 = 200;
    end
    if ~get(WF.rbh3,'value')
        cdt3 = 200;
    end
    if ~get(WF.rbh4,'value')
        cdt4 = 200;
    end
    if ~get(WF.rbh5,'value')
        cdt5 = 200;
    end
    if ~get(WF.rbh6,'value')
        cdt6 = 200;
    end
    if ~get(WF.rbh7,'value')
        cdt7 = 200;
    end
    if ~get(WF.rbh8,'value')
        cdt8 = 200;
    end
    if ~get(WF.rbh9,'value')
        cdt9 = 200;
    end
    if ~get(WF.rbh10,'value')
        cdt10 = 200;
    end
    switch get(WF.hpmwtype,'value');
        case 1
            wavestr = 'db2';
        case 2
            wavestr = 'db10';
        case 3
            wavestr = 'sym2';
        case 4
            wavestr = 'haar';
    end
    WF.signal = WF.ECG(get(WF.hpmlead,'value'),:);

    switch get(WF.hpmwthrhd,'value')
        case 1
            SORH = 's';
        case 2
            SORH = 'h';
    end
    WF.wavestr = wavestr;
    WF.SORH = SORH;
    WF.T = [cdt1 cdt2 cdt3 cdt4 cdt5 cdt6 cdt7 cdt8 cdt9 cdt10];
    set(WF.design_but,'enable','on');
    set(fig,'userdata',WF);


elseif strcmp(cmd,'plot')
    wavestr = WF.wavestr;
    SORH = WF.SORH;
    y = WF.signal;
    scale = 10;
    N = 1:10;
    T = WF.T;

    [C,L] = wavedec(y,scale,wavestr);
    Apr = wrcoef('a',C,L,wavestr,scale);
    for i=1:scale
        D(i,:) = wrcoef('d',C,L,wavestr,i);
    end

    NC = wthcoef('t',C,L,N,T,SORH);
    NC = wthcoef('a',NC,L);

    for i=1:scale
        ND(i,:) = wrcoef('d',NC,L,wavestr,i);
    end
    y2 = waverec(NC,L,wavestr);

    axes(WF.oriplot);
    cla;
    ori_x = 1:length(y);
    ori_x = ori_x./1000;
    plot(ori_x,y); hold on; plot(ori_x,y2,'r');hold off;
    set(WF.oriplot,'XLim',[0 length(y)/1000],'Visible','on','FontSize',6)

    axes(WF.d1plot);
    cla;
    plot(D(1,:)); hold on; plot(ND(1,:),'r');hold off;
    set(WF.d1plot,'XLim',[0 length(y)],'Visible','off')

    axes(WF.d2plot);
    cla;
    plot(D(2,:)); hold on; plot(ND(2,:),'r');hold off;
    set(WF.d2plot,'XLim',[0 length(y)],'Visible','off')

    axes(WF.d3plot);
    cla;
    plot(D(3,:)); hold on; plot(ND(3,:),'r');hold off;
    set(WF.d3plot,'XLim',[0 length(y)],'Visible','off')

    axes(WF.d4plot);
    cla;
    plot(D(4,:)); hold on; plot(ND(4,:),'r');hold off;
    set(WF.d4plot,'XLim',[0 length(y)],'Visible','off')

    axes(WF.d5plot);
    cla;
    plot(D(5,:)); hold on; plot(ND(5,:),'r');hold off;
    set(WF.d5plot,'XLim',[0 length(y)],'Visible','off')

    axes(WF.d6plot);
    cla;
    plot(D(6,:)); hold on; plot(ND(6,:),'r');hold off;
    set(WF.d6plot,'XLim',[0 length(y)],'Visible','off')

    axes(WF.d7plot);
    cla;
    plot(D(7,:)); hold on; plot(ND(7,:),'r');hold off;
    set(WF.d7plot,'XLim',[0 length(y)],'Visible','off')

    axes(WF.d8plot);
    cla;
    plot(D(8,:)); hold on; plot(ND(8,:),'r');hold off;
    set(WF.d8plot,'XLim',[0 length(y)],'Visible','off')

    axes(WF.d9plot);
    cla;
    plot(D(9,:)); hold on; plot(ND(9,:),'r');hold off;
    set(WF.d9plot,'XLim',[0 length(y)],'Visible','off')

    axes(WF.d10plot);
    cla;
    plot(D(10,:)); hold on; plot(ND(10,:),'r');hold off;
    set(WF.d10plot,'XLim',[0 length(y)],'Visible','off')

    set(WF.OK_but,'enable','on');
    set(WF.Close_but,'enable','on');

elseif strcmp(cmd,'ok')
    wfilter.wavestr = WF.wavestr;
    wfilter.SORH = WF.SORH;
    wfilter.scale = 10;
    wfilter.N = 1:10;
    wfilter.T = WF.T;
    std_signal_processing('import_filter',wfilter,strcat('wfilter',num2str(WF.filterno)));

    set(fig,'userdata',WF);
    if exist(cat(2,tempdir,'waveletGUIdata.mat'))
        delete(cat(2,tempdir,'waveletGUIdata.mat'));
    end
    delete(fig);
end



function default = getdefaults
default.rb1 = 1;
default.rb2 = 1;
default.rb3 = 1;
default.rb4 = 1;
default.rb5 = 1;
default.rb6 = 1;
default.rb7 = 1;
default.rb8 = 1;
default.rb9 = 1;
default.rb10 = 1;
default.wavestr = 'db2';
default.SORH = 's';
default.scale = 10;
default.N = [1 2 3 4 5 6 7 8 9 10];
default.T = [0 0 0 0 0 0 0 0 0 0];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Defune positions for all GUI parts
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function uipos = getuipos
tlabelw = 25;
labelw = 32;
editw = 12;
border = 1.3333;
labelh = 1.5;
edith = 1.53846;

figw = 160;
figh = 50;


sunits = get(0, 'Units');
set (0, 'Units', 'character');
ssinchar = get(0, 'ScreenSize');
set (0, 'Units', sunits);

figl = (ssinchar(3) - figw) / 2;
figb = (ssinchar(4) - figh) / 2;

uipos.fig = [figl,figb,figw,figh];
labell = (figw-tlabelw)/2;
framew = figw - (border*2);

uipos.frame1 = [border,0.6+2*border,framew/4,42];

uipos.Title_waveletGUI = [(figw-framew)/2,46.2,framew,2.23077];
uipos.error_messages = [border+(0.3*border),0.38,framew-52,1.6];
uipos.frame2 = [border,0.28,framew-50,2.25128];


uipos.hfs = [border+0.6*border,42,tlabelw-3,edith];
uipos.hetfs = [border+tlabelw-3,42.2,editw-2,edith];
uipos.hfs1 = [border+tlabelw+editw-2,42,tlabelw-22,edith];

uipos.hlead = [border+0.6*border,39.5,tlabelw-9,labelh];
uipos.hpmlead = [border+tlabelw-3,39.7,tlabelw-9,labelh];

uipos.hwavetype = [border+0.6*border,36.5,tlabelw-9,labelh];
uipos.hpmwtype = [border+tlabelw-3,36.7,tlabelw-9,labelh];

uipos.hwavethrhd = [border+0.6*border,33.5,tlabelw-3,labelh];
uipos.hpmwthrhd = [border+tlabelw-3,33.7,tlabelw-9,labelh];

uipos.oriplot = [5*border+framew/4,37.8,3*framew/4-6,8];
uipos.d1plot = [5*border+framew/4,30.7,3*framew/8-6,6];
uipos.d1txt = [1.5*border+framew/4,34.5,tlabelw-21,edith-0.4];

uipos.d2plot = [5*border+framew/4,23.9,3*framew/8-6,6];
uipos.d2txt = [1.5*border+framew/4,27.7,tlabelw-21,edith-0.4];

uipos.d3plot = [5*border+framew/4,17.1,3*framew/8-6,6];
uipos.d3txt = [1.5*border+framew/4,20.9,tlabelw-21,edith-0.4];

uipos.d4plot = [5*border+framew/4,10.3,3*framew/8-6,6];
uipos.d4txt = [1.5*border+framew/4,14.1,tlabelw-21,edith-0.4];

uipos.d5plot = [5*border+framew/4,3.5,3*framew/8-6,6];
uipos.d5txt = [1.5*border+framew/4,7.3,tlabelw-21,edith-0.4];

uipos.d6plot = [5*border+framew/4+3*framew/8,30.7,3*framew/8-6,6];
uipos.d6txt = [1.5*border+framew/4+3*framew/8,34.5,tlabelw-21,edith-0.4];

uipos.d7plot = [5*border+framew/4+3*framew/8,23.9,3*framew/8-6,6];
uipos.d7txt = [1.5*border+framew/4+3*framew/8,27.7,tlabelw-21,edith-0.4];

uipos.d8plot = [5*border+framew/4+3*framew/8,17.1,3*framew/8-6,6];
uipos.d8txt = [1.5*border+framew/4+3*framew/8,20.9,tlabelw-21,edith-0.4];

uipos.d9plot = [5*border+framew/4+3*framew/8,10.3,3*framew/8-6,6];
uipos.d9txt = [1.5*border+framew/4+3*framew/8,14.1,tlabelw-21,edith-0.4];

uipos.d10plot = [5*border+framew/4+3*framew/8,3.5,3*framew/8-6,6];
uipos.d10txt = [1.5*border+framew/4+3*framew/8,7.3,tlabelw-21,edith-0.4];

uipos.bandselection = [border+0.6*border,30.5,tlabelw-8,labelh];
uipos.rbh1 = [border+4*border,28,tlabelw-3,labelh];
uipos.hetrb1 = [border+tlabelw-9,28,tlabelw-11,labelh];

uipos.rbh2 = [border+4*border,25.8,tlabelw-3,labelh];
uipos.hetrb2 = [border+tlabelw-9,25.8,tlabelw-11,labelh];

uipos.rbh3 = [border+4*border,23.6,tlabelw-3,labelh];
uipos.hetrb3 = [border+tlabelw-9,23.6,tlabelw-11,labelh];

uipos.rbh4 = [border+4*border,21.4,tlabelw-3,labelh];
uipos.hetrb4 = [border+tlabelw-9,21.4,tlabelw-11,labelh];

uipos.rbh5 = [border+4*border,19.2,tlabelw-3,labelh];
uipos.hetrb5 = [border+tlabelw-9,19.2,tlabelw-11,labelh];

uipos.rbh6 = [border+4*border,17,tlabelw-3,labelh];
uipos.hetrb6 = [border+tlabelw-9,17,tlabelw-11,labelh];

uipos.rbh7 = [border+4*border,14.8,tlabelw-3,labelh];
uipos.hetrb7 = [border+tlabelw-9,14.8,tlabelw-11,labelh];

uipos.rbh8 = [border+4*border,12.6,tlabelw-3,labelh];
uipos.hetrb8 = [border+tlabelw-9,12.6,tlabelw-11,labelh];

uipos.rbh9 = [border+4*border,10.4,tlabelw-3,labelh];
uipos.hetrb9 = [border+tlabelw-9,10.4,tlabelw-11,labelh];

uipos.rbh10 = [border+4*border,8.2,tlabelw-3,labelh];
uipos.hetrb10 = [border+tlabelw-9,8.2,tlabelw-11,labelh];

uipos.design_but = [border+tlabelw-15,5.5,17.6004,1.64103];


uipos.Close_but = [figw-24,0.5,17.6004,1.64103];
uipos.OK_but = [figw-44,0.5,17.6004,1.64103];

